In [52]:
import pandas as pd

#main dataset example
spotify_mockup_df = pd.read_csv("../spotify_gabby.csv")
#backup dataset
albums_df = pd.read_csv("../dataset/albums.csv")
artist_df = pd.read_csv("../dataset/artists.csv")

In [2]:
print(spotify_mockup_df.shape)
spotify_mockup_df.head()

(100, 17)

,Unnamed: 0,name,album,artist,release_date,length,popularity,danceability,acousticness,danceability.1,energy,instrumentalness,liveness,loudness,speechiness,tempo,time_signature
0,0,The Spark,Deceiver,DIIV,2019-10-04,239213,13,0.385,0.000064,0.385,0.819,0.545000,0.2040,-6.061,0.0497,140.016,4
1,1,She,She,Alice Phoebe Lou,2018-02-23,235515,54,0.358,0.117000,0.358,0.579,0.010900,0.0899,-8.718,0.0388,128.411,4
2,2,Nostalgia,Paper Castles,Alice Phoebe Lou,2019-03-08,197950,50,0.440,0.692000,0.440,0.256,0.000000,0.2440,-8.731,0.0342,121.634,4
3,3,Paper Castles,Paper Castles,Alice Phoebe Lou,2019-03-08,234871,35,0.571,0.214000,0.571,0.406,0.060700,0.1190,-9.097,0.0414,83.894,4
4,4,Something Holy,Paper Castles,Alice Phoebe Lou,2019-03-08,286172,51,0.411,0.284000,0.411,0.470,0.000002,0.0765,-6.821,0.0319,131.734,4

In [3]:
print(albums_df.shape)
albums_df.head(5)

(100000, 10)

,id,artist_id,album_title,genre,year_of_pub,num_of_tracks,num_of_sales,rolling_stone_critic,mtv_critic,music_maniac_critic
0,1,1767,Call me Cat Moneyless That Doggies,Folk,2006,11,905193,4.0,1.5,3.0
1,2,23548,Down Mare,Metal,2014,7,969122,3.0,4.0,5.0
2,3,17822,Embarrassed Hungry,Latino,2000,11,522095,2.5,1.0,2.0
3,4,19565,Standard Immediate Engineer Slovakia,Pop,2017,4,610116,1.5,2.0,4.0
4,5,24941,Decent Distance Georgian,Black Metal,2010,8,151111,4.5,2.5,1.0

In [4]:
print(artist_df.shape)
artist_df.head(5)

(50000, 9)

,id,real_name,art_name,role,year_of_birth,country,city,email,zip_code
0,1,Kameko Nelson,NaN,female voice,1981,Slovenia,Vedrin,lorem.tristique.aliquet@nonummyFusce.co.uk,6914
1,2,Sacha Cameron,Bianco Ibureno Chloride,artist,1955,Guernsey,Montigny-le-Tilleul,Sed@elementum.com,0568
2,3,Thane E. Oliver,NaN,rapper,1993,Guinea-Bissau,Saint-Sébastien-sur-Loire,Integer.tincidunt.aliquam@libero.com,813154
3,4,Cole E. Joseph,Persian responsible,bassist,1994,Estonia,Newquay,nulla.magna.malesuada@vulputate.com,A4S 2B3
4,5,Sonia U. Jensen,Asleep lonely Big Morgan,DJ,1988,Vanuatu,Dudzele,faucibus@euismodetcommodo.edu,46418

# For Spotify dataset

## Create a list of Mood and put them into each data randomly as mockup

In [50]:
Mood = ['Dark','Relaxing','Energetic','Happy','Aggressive']
from random import seed
from random import randint
import numpy as np
seed(1)
Mood_mockup = ["NA"]*spotify_mockup_df.shape[0]
list_value = np.arange(100)
for i in list(range(100)):
    list_value[i] = randint(0,4)
    Mood_mockup[i] = Mood[list_value[i]]
Mood_mockup_df = pd.DataFrame(Mood_mockup,columns=['Mood'])
Mood_Index_mockup_df = pd.DataFrame(list_value,columns=['Mood_Index'])

In [53]:
spotify_mockup_df = spotify_mockup_df.merge(Mood_mockup_df,right_index=True,left_index=True)
spotify_mockup_df = spotify_mockup_df.merge(Mood_Index_mockup_df,right_index=True,left_index=True)
spotify_mockup_df.head()

,Unnamed: 0,name,album,artist,release_date,length,popularity,danceability,acousticness,danceability.1,energy,instrumentalness,liveness,loudness,speechiness,tempo,time_signature,Mood,Mood_Index
0,0,The Spark,Deceiver,DIIV,2019-10-04,239213,13,0.385,0.000064,0.385,0.819,0.545000,0.2040,-6.061,0.0497,140.016,4,Relaxing,1
1,1,She,She,Alice Phoebe Lou,2018-02-23,235515,54,0.358,0.117000,0.358,0.579,0.010900,0.0899,-8.718,0.0388,128.411,4,Aggressive,4
2,2,Nostalgia,Paper Castles,Alice Phoebe Lou,2019-03-08,197950,50,0.440,0.692000,0.440,0.256,0.000000,0.2440,-8.731,0.0342,121.634,4,Dark,0
3,3,Paper Castles,Paper Castles,Alice Phoebe Lou,2019-03-08,234871,35,0.571,0.214000,0.571,0.406,0.060700,0.1190,-9.097,0.0414,83.894,4,Energetic,2
4,4,Something Holy,Paper Castles,Alice Phoebe Lou,2019-03-08,286172,51,0.411,0.284000,0.411,0.470,0.000002,0.0765,-6.821,0.0319,131.734,4,Dark,0

## Mockup Model for Machine Learning

Variable 'Mood' has the real name of each mood and 'Mood_Index' is the numerical categories of moods.

In [75]:
# Remove some non-numerical variables
spotify_mockup_df_cleaned = spotify_mockup_df.drop(labels=['Unnamed: 0','name','album','artist','release_date'],axis=1)
spotify_mockup_df_cleaned.head()

,length,popularity,danceability,acousticness,danceability.1,energy,instrumentalness,liveness,loudness,speechiness,tempo,time_signature,Mood,Mood_Index
0,239213,13,0.385,0.000064,0.385,0.819,0.545000,0.2040,-6.061,0.0497,140.016,4,Relaxing,1
1,235515,54,0.358,0.117000,0.358,0.579,0.010900,0.0899,-8.718,0.0388,128.411,4,Aggressive,4
2,197950,50,0.440,0.692000,0.440,0.256,0.000000,0.2440,-8.731,0.0342,121.634,4,Dark,0
3,234871,35,0.571,0.214000,0.571,0.406,0.060700,0.1190,-9.097,0.0414,83.894,4,Energetic,2
4,286172,51,0.411,0.284000,0.411,0.470,0.000002,0.0765,-6.821,0.0319,131.734,4,Dark,0

In [76]:
x_columns = spotify_mockup_df_cleaned.drop(labels=['Mood','Mood_Index'],axis=1).columns

There are two options for machine learning model: Logistic Regression Moel and Neural Network Model

### Logistic Regression Model:
The basic logistic regression model only deals with binary classification. However, our dataset has 5 different types of mood. One idea is to transform each mood into boelen variable (0=no,1=yes) like one-hot encoded features. Then we can fit five logistic regression models for each mood to obtain a list possible mood for each song. The second idea is to use multinomial logistic regression which can deal with mutlti-classification situation.

#### Basic Logistic Regression Model:

In [77]:
spotify_mockup_df_BLR = spotify_mockup_df_cleaned.drop(labels=['Mood_Index'],axis=1)
spotify_mockup_df_BLR.head(1)

,length,popularity,danceability,acousticness,danceability.1,energy,instrumentalness,liveness,loudness,speechiness,tempo,time_signature,Mood
0,239213,13,0.385,0.000064,0.385,0.819,0.545,0.204,-6.061,0.0497,140.016,4,Relaxing

In [78]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
spotify_mockup_df_cat = spotify_mockup_df_BLR.dtypes[spotify_mockup_df_BLR.dtypes == 'object'].index.tolist()
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)
# Fit and transform the OneHotEncoder using the categorical variable list
encode_df = pd.DataFrame(enc.fit_transform(spotify_mockup_df_BLR[spotify_mockup_df_cat]))
# Add the encoded variable names to the dataframe
encode_df.columns = enc.get_feature_names_out(spotify_mockup_df_cat)
encode_df.head()

   Mood_Aggressive  Mood_Dark  Mood_Energetic  Mood_Happy  Mood_Relaxing
0              0.0        0.0             0.0         0.0            1.0
1              1.0        0.0             0.0         0.0            0.0
2              0.0        1.0             0.0         0.0            0.0
3              0.0        0.0             1.0         0.0            0.0
4              0.0        1.0             0.0         0.0            0.0

In [79]:
spotify_mockup_df_BLR = spotify_mockup_df_BLR.merge(encode_df,left_index=True,right_index=True)
spotify_mockup_df_BLR = spotify_mockup_df_BLR.drop(labels=spotify_mockup_df_cat,axis=1)
spotify_mockup_df_BLR.head()

,length,popularity,danceability,acousticness,danceability.1,energy,instrumentalness,liveness,loudness,speechiness,tempo,time_signature,Mood_Aggressive,Mood_Dark,Mood_Energetic,Mood_Happy,Mood_Relaxing
0,239213,13,0.385,0.000064,0.385,0.819,0.545000,0.2040,-6.061,0.0497,140.016,4,0.0,0.0,0.0,0.0,1.0
1,235515,54,0.358,0.117000,0.358,0.579,0.010900,0.0899,-8.718,0.0388,128.411,4,1.0,0.0,0.0,0.0,0.0
2,197950,50,0.440,0.692000,0.440,0.256,0.000000,0.2440,-8.731,0.0342,121.634,4,0.0,1.0,0.0,0.0,0.0
3,234871,35,0.571,0.214000,0.571,0.406,0.060700,0.1190,-9.097,0.0414,83.894,4,0.0,0.0,1.0,0.0,0.0
4,286172,51,0.411,0.284000,0.411,0.470,0.000002,0.0765,-6.821,0.0319,131.734,4,0.0,1.0,0.0,0.0,0.0

Using Mood_Aggressive as exmaple

In [80]:
# Split our preprocessed data into our features and target arrays
y = spotify_mockup_df_BLR['Mood_Aggressive'].values
X = spotify_mockup_df_BLR[x_columns].values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [81]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [82]:
# Define the logistic regression model
log_classifier = LogisticRegression(solver="lbfgs",max_iter=200)

# Train the model
log_classifier.fit(X_train,y_train)

# Evaluate the model
y_pred = log_classifier.predict(X_test)
print(f" Logistic regression model accuracy: {accuracy_score(y_test,y_pred):.3f}")

 Logistic regression model accuracy: 0.680

#### Mutinomial Logistic Regression

In [83]:
from sklearn.datasets import make_classification
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold

In [95]:
spotify_mockup_df_cleaned["Mood_Index"] = spotify_mockup_df_cleaned["Mood_Index"].astype(float)
y = spotify_mockup_df_cleaned["Mood_Index"].values
X = spotify_mockup_df_cleaned[x_columns].values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [101]:
# define the multinomial logistic regression model
model = LogisticRegression(multi_class='multinomial', solver='lbfgs')
model.fit(X_train_scaled,y_train)
# report the model performance
y_pred = model.predict(X_test_scaled)
print(f" Logistic regression model accuracy: {accuracy_score(y_test,y_pred):.3f}")

 Logistic regression model accuracy: 0.240

#### Neural Network Model

In [107]:
import tensorflow as tf
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train[0])
hidden_nodes_layer1 = 10
hidden_nodes_layer2 = 6

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=5, activation="softmax"))

# Check the structure of the model
nn.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_3 (Dense)              (None, 10)                130
_________________________________________________________________
dense_4 (Dense)              (None, 6)                 66
_________________________________________________________________
dense_5 (Dense)              (None, 5)                 35
=================================================================
Total params: 231
Trainable params: 231
Non-trainable params: 0
_________________________________________________________________

In [108]:
# Compile the model
nn.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

In [115]:
from tensorflow import keras 
y_int = y_train.astype(int)
y_train_cat = keras.utils.to_categorical(y_int)
y_test_cat = keras.utils.to_categorical(y_test.astype(int))

In [114]:
# Train the model
fit_model = nn.fit(X_train_scaled,y_train_cat,epochs=50)

Train on 75 samples
Epoch 1/50
75/75 [==============================] - 0s 5ms/sample - loss: 1.7931 - accuracy: 0.2000
Epoch 2/50
75/75 [==============================] - 0s 69us/sample - loss: 1.7785 - accuracy: 0.2000
Epoch 3/50
75/75 [==============================] - 0s 102us/sample - loss: 1.7654 - accuracy: 0.2000
Epoch 4/50
75/75 [==============================] - 0s 85us/sample - loss: 1.7519 - accuracy: 0.2000
Epoch 5/50
75/75 [==============================] - 0s 74us/sample - loss: 1.7398 - accuracy: 0.2000
Epoch 6/50
75/75 [==============================] - 0s 87us/sample - loss: 1.7288 - accuracy: 0.2000
Epoch 7/50
75/75 [==============================] - 0s 87us/sample - loss: 1.7169 - accuracy: 0.2000
Epoch 8/50
75/75 [==============================] - 0s 102us/sample - loss: 1.7056 - accuracy: 0.2000
Epoch 9/50
75/75 [==============================] - 0s 92us/sample - loss: 1.6948 - accuracy: 0.2000
Epoch 10/50
75/75 [==============================] - 0s 86us/sample - loss: 1.6856 - accuracy: 0.2000
Epoch 11/50
75/75 [==============================] - 0s 93us/sample - loss: 1.6754 - accuracy: 0.2000
Epoch 12/50
75/75 [==============================] - 0s 96us/sample - loss: 1.6668 - accuracy: 0.2000
Epoch 13/50
75/75 [==============================] - 0s 108us/sample - loss: 1.6585 - accuracy: 0.2000
Epoch 14/50
75/75 [==============================] - 0s 111us/sample - loss: 1.6506 - accuracy: 0.2000
Epoch 15/50
75/75 [==============================] - 0s 90us/sample - loss: 1.6429 - accuracy: 0.2000
Epoch 16/50
75/75 [==============================] - 0s 103us/sample - loss: 1.6366 - accuracy: 0.2133
Epoch 17/50
75/75 [==============================] - 0s 88us/sample - loss: 1.6296 - accuracy: 0.2133
Epoch 18/50
75/75 [==============================] - 0s 75us/sample - loss: 1.6235 - accuracy: 0.2133
Epoch 19/50
75/75 [==============================] - 0s 86us/sample - loss: 1.6180 - accuracy: 0.2133
Epoch 20/50
75/75 [==============================] - 0s 74us/sample - loss: 1.6130 - accuracy: 0.2133
Epoch 21/50
75/75 [==============================] - 0s 66us/sample - loss: 1.6073 - accuracy: 0.2400
Epoch 22/50
75/75 [==============================] - 0s 79us/sample - loss: 1.6030 - accuracy: 0.2400
Epoch 23/50
75/75 [==============================] - 0s 80us/sample - loss: 1.5991 - accuracy: 0.2400
Epoch 24/50
75/75 [==============================] - 0s 83us/sample - loss: 1.5947 - accuracy: 0.2400
Epoch 25/50
75/75 [==============================] - 0s 70us/sample - loss: 1.5910 - accuracy: 0.2533
Epoch 26/50
75/75 [==============================] - 0s 70us/sample - loss: 1.5875 - accuracy: 0.2533
Epoch 27/50
75/75 [==============================] - 0s 91us/sample - loss: 1.5840 - accuracy: 0.2533
Epoch 28/50
75/75 [==============================] - 0s 73us/sample - loss: 1.5806 - accuracy: 0.2533
Epoch 29/50
75/75 [==============================] - 0s 75us/sample - loss: 1.5773 - accuracy: 0.2667
Epoch 30/50
75/75 [==============================] - 0s 71us/sample - loss: 1.5743 - accuracy: 0.2667
Epoch 31/50
75/75 [==============================] - 0s 79us/sample - loss: 1.5714 - accuracy: 0.2667
Epoch 32/50
75/75 [==============================] - 0s 66us/sample - loss: 1.5686 - accuracy: 0.2667
Epoch 33/50
75/75 [==============================] - 0s 88us/sample - loss: 1.5653 - accuracy: 0.2667
Epoch 34/50
75/75 [==============================] - 0s 107us/sample - loss: 1.5628 - accuracy: 0.2533
Epoch 35/50
75/75 [==============================] - 0s 84us/sample - loss: 1.5600 - accuracy: 0.2800
Epoch 36/50
75/75 [==============================] - 0s 83us/sample - loss: 1.5571 - accuracy: 0.2800
Epoch 37/50
75/75 [==============================] - 0s 80us/sample - loss: 1.5547 - accuracy: 0.2800
Epoch 38/50
75/75 [==============================] - 0s 85us/sample - loss: 1.5523 - accuracy: 0.2800
Epoch 39/50
75/75 [==============================] - 0s 88us/sample - loss: 1.5496 - accuracy: 0.2800
Epoch 40/50
75/75 [==============================] - 0s 74us/sample - loss: 1.5474 - accuracy: 0.2933
Epoch 41/50
75/75 [==============================] - 0s 80us/sample - loss: 1.5452 - accuracy: 0.2933
Epoch 42/50
75/75 [==============================] - 0s 149us/sample - loss: 1.5430 - accuracy: 0.2933
Epoch 43/50
75/75 [==============================] - 0s 117us/sample - loss: 1.5405 - accuracy: 0.2933
Epoch 44/50
75/75 [==============================] - 0s 123us/sample - loss: 1.5384 - accuracy: 0.2933
Epoch 45/50
75/75 [==============================] - 0s 83us/sample - loss: 1.5360 - accuracy: 0.2933
Epoch 46/50
75/75 [==============================] - 0s 89us/sample - loss: 1.5340 - accuracy: 0.2933
Epoch 47/50
75/75 [==============================] - 0s 91us/sample - loss: 1.5317 - accuracy: 0.2933
Epoch 48/50
75/75 [==============================] - 0s 81us/sample - loss: 1.5296 - accuracy: 0.2800
Epoch 49/50
75/75 [==============================] - 0s 87us/sample - loss: 1.5270 - accuracy: 0.2933
Epoch 50/50
75/75 [==============================] - 0s 92us/sample - loss: 1.5252 - accuracy: 0.2933

In [116]:
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test_cat,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

25/1 - 0s - loss: 1.6075 - accuracy: 0.1600
Loss: 1.6075050830841064, Accuracy: 0.1599999964237213